#!/usr/bin/env bash
# Clear environment script

set -o errexit
set -o xtrace

echo '####################################################'
echo 'Stopping running containers (if available)...'
echo '####################################################'
docker stop "$(docker ps -aq)"

# remove all stopped containers
echo '####################################################'
echo 'Removing containers ..'
echo '####################################################'
docker rm "$(docker ps -aq)"


# remove all images
echo '####################################################'
echo 'Removing images ...'
echo '####################################################'
docker rmi "$(docker images -q)"

# remove all stray volumes if any
echo '####################################################'
echo 'Revoming docker container volumes (if any)'
echo '####################################################'
docker volume rm "$(docker volume ls -q)"

echo "Environment has just been cleaned"
exit 0
