#!/usr/bin/env bash

set -o errexit
set -o xtrace

main() {
  if [[ ${EUID} != 0 ]]; then
      echo "Must be executed as root"
  else
      sudo docker stack deploy -c docker-stack.yml arrebol
      exit 0
  fi
}

main
