#!/usr/bin/env bash

set -o errexit
set -o xtrace

_install_docker() {
    sudo wget -qO- https://get.docker.com | sh

    sudo /etc/init.d/docker status

    sudo groupadd docker

    sudo usermod -aG docker "$USER"

    sudo service docker restart
}

readonly ENV_FILE_PATH="../.env"

main() {
  if [[ ${EUID} != 0 ]]; then
      echo "Must be executed as root"
  else
       #_install_docker

      if [[ -f "${ENV_FILE_PATH}" ]]; then
          echo "Env file don't found"
          exit 1
      else
          cp ${ENV_FILE_PATH} ./docker
          sudo docker stack deploy -c docker-stack.yml arrebol
          exit 0
      fi
  fi
}

main